[project]
name = "install-interface"
authors = ["Install Interface Team"]
description = "A decentralized governance platform for collaborative software interface development"
telemetry = false
requirements = []

[contracts.interface-manager]
path = "contracts/interface-manager.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false